### ISSUE TITLE
bin/test_sugardough_docker.sh leaves running containers

### ISSUE THREAD

**Issue by jgmize** [mozilla/sugardough#118]
I noticed there were 38 running containers left over from https://ci.us-west.moz.works/view/Sugardough/job/sugardough/ that needed to be manually killed. To do this I ran the following:
```sh
for i in $(sudo docker ps | grep sugardough | awk '{print $1}'); do 
    sudo docker stop $i;
done
```
Upon further investigation I noticed a post-build action with the command ```docker rm -f `echo jenkins${JOB_NAME}${BUILD_NUMBER}| sed s/_//g`_db_1``` but the running containers all ended in `_db_run_1`, not `_db_1`, so I changed the post-build action. I'm noting that here to record the change, but I think the cleanup command should be a script in this repo, and I'll follow up with a PR to add it.

**Comment by glogiotatidis** [comment]
Actually the issue is that the test script was executing `docker-compose run db` instead of `docker-compose up db`. Later the `docker-compose run web` would generate another container with the name `_db_1`. 

The cleanup script is correct, all we need to do is change `run db` to `up db`. I created #120 to fix it.

Thanks for investigating this @jgmize

**Comment by jgmize** [comment]
Verified that changes in fcebed9 successfully removed the docker containers after https://ci.us-west.moz.works/view/Sugardough/job/sugardough/358/console
