### ISSUE TITLE
To session_csrf or not to session_csrf

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/sugardough#38]
I'm migrating a project from playdoh with django 1.4, doing so by creating a fresh sugardough site and then bringing over pieces from both the site and playdoh as needed.

The current site uses session_csrf, which is standard for playdoh, so I brought this over as well. I was wondering:

1. Is this something that we should include as standard in sugardough? If so I can create a PR.
2. Is there something else that can be done with django 1.7 that would eliminate the need for session_csrf, and/or is there an alternate/better solution to the problem it addresses?

**Comment by pmclanahan** [comment]
For reference: https://github.com/mozilla/django-session-csrf

**Comment by Osmose** [comment]
I vote for including it; with pure cookie-based CSRF, the issue is that any *.mozilla.org site with a vulnerability can allow a malicious party to set a CSRF cookie and then trick the user into POSTing to your site, bypassing your CSRF protection. 

When the token is in the session, they can't forge a fake token, and since they're on another domain, they can't get the real token, thus they can't trick the user into making a proper POST.

**Comment by glogiotatidis** [comment]
See also https://docs.djangoproject.com/en/dev/ref/csrf/#limitations which repeats what @Osmose said.

+1 on including it
